### ISSUE TITLE
foreach error on 10.0.22-MariaDB

### ISSUE THREAD

**Issue by pleiadess** [shlomi-noach/common_schema#1] opened 2015-12-05 11:28 UTC
Executing this:

CALL foreach( 
"SELECT TABLE_SCHEMA 
FROM INFORMATION_SCHEMA.TABLES WHERE table_name LIKE 'devices'",
"SELECT `username`, `group`, `acl_group_id` FROM ${1}.users");

MySQL Version                 : 10.0.21-MariaDB ---> works fine

MySQL Version                 : 10.0.22-MariaDB ---> error:

1 queries executed, 0 success, 1 errors, 0 warnings

Query: CALL foreach( "SELECT TABLE_SCHEMA  FROM INFORMATION_SCHEMA.TABLES  WHERE table_name LIKE 'devices'", "SELECT  `username`, `grou...

Error Code: 1644
QueryScript error: [Unsupported token: "startg"] at 7: "SELECT 
`username`, `group`, `acl_group_id` FROM abm.users "

**Comment by alexkipkalo** [comment] 2015-12-09 17:40
Similar issue on my side: 

CALL `common_schema`.`foreach`(
"SELECT table_schema FROM INFORMATION_SCHEMA.TABLES WHERE table_name = '<table_name>' ",
"UPDATE `${1}`.<table_name> set ...... WHERE id = <id> ");

> show warnings ;
Error Code: 1644 ; 
Message : QueryScript error: [Unsupported token: "sleep-"] at 7: "UPDATE ... ";

MySQL version : Percona 5.6.23-72.1 -- no error ;
MySQL version : Percona 5.6.27-rel75 -- error ;

**Comment by alexkipkalo** [comment] 2016-03-02 19:50
Do you know what it might be ?

**Comment by tersmitten** [comment] 2016-03-07 08:40
I think we have the same error, [see](https://travis-ci.org/Oefenweb/ansible-common-schema/jobs/113779489#L520).

Do you have any suggestions @shlomi-noach?

**Comment by ikewalker** [comment] 2016-03-16 21:18
I've tested this in 5.7 and gotten similar errors.

Looking more closely at 5.6, I tested each version of community server between 5.6.22 and 5.6.27, and 5.6.27 was the first version that started throwing the error.

So it appears to be a change between 5.6.26 and 5.6.27 that broke QueryScript.

**Comment by shlomi-noach** [comment] 2016-03-31 13:12
I can also confirm:
```
master [localhost] {msandbox} (common_schema) > call run("foreach ($s: select TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE table_name LIKE 'samplet') {select * from ${1}.samplet}" );
ERROR 1644 (91100): QueryScript error: [Unsupported token: "startet"] at 8: "foreach ($s: select TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE t
master [localhost] {msandbox} (common_schema) > call run("foreach ($s: select TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE table_name LIKE 'samplet') {select * from ${1}.samplet}" );
ERROR 1644 (91100): QueryScript error: [Unsupported token: "
```

I'm looking into this. I cannot see an obvious hint in http://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-27.html

**Comment by shlomi-noach** [comment] 2016-03-31 13:21
```
master [localhost] {msandbox} (common_schema) > call run('select * from _sql_tokens');
ERROR 1644 (91100): QueryScript error: [Unsupported token: "startt"] at 7: "select * from _sql_tokens"
master [localhost] {msandbox} (common_schema) > call run('select * from _sql_tokens');
ERROR 1644 (91100): QueryScript error: [Unsupported token: "
```

**Comment by tersmitten** [comment] 2016-03-31 13:52
We're also experiencing the problem in mysql 5.5 ([5.5.46](https://travis-ci.org/Oefenweb/ansible-common-schema/jobs/113779489#L47))

**Comment by shlomi-noach** [comment] 2016-03-31 14:13
Seems like MySQL introduced a bug in local routine variables.

These variables:
```
    declare first_token text;
    declare first_state text;
```

Are assigned via:
```
SELECT level, token, state FROM _sql_tokens WHERE id = id_from INTO statement_level, first_token, first_state;``` 

With these legit values, `select`, `alpha` (first row):
```
+-----------+------------+----+-------+-------+--------+------------+
| server_id | session_id | id | start | level | token  | state      |
+-----------+------------+----+-------+-------+--------+------------+
|         1 |         19 |  1 |     7 |     0 | select | alpha      |
|         1 |         19 |  2 |     8 |     0 |        | whitespace |
|         1 |         19 |  3 |     9 |     0 | 1      | integer    |
|         1 |         19 |  4 |     9 |     0 |        | start      |
+-----------+------------+----+-------+-------+--------+------------+
```
and their values are _immediately_ corrupted.

I'm looking to see whether I can overcome this bug, but it is very disconcerting as this coding style is all over the place.

**Comment by shlomi-noach** [comment] 2016-03-31 14:18
This seems to work around the problem:
```
      SELECT level, token, state FROM _sql_tokens WHERE id = id_from INTO @_statement_level, @_first_token, @_first_state;

      set statement_level=@_statement_level;
      set first_token=@_first_token;
      set first_state=@_first_state;
```

**Comment by shlomi-noach** [comment] 2016-03-31 14:41
O-M-G this is _everywhere_. This bug is creepy and happens on multiple occasions of `SELECT... INTO <local-variable>`. I'm replacing all occurrences, but I'm doing so hastily at this time.
I will need to step back and do this orderly. Meanwhile I can throw in a hopefully mostly fixed deployment file.

**Comment by shlomi-noach** [comment] 2016-04-01 09:02
Please find new `sql` file in https://github.com/shlomi-noach/common_schema/releases/tag/v2.3

**Comment by tersmitten** [comment] 2016-04-01 10:23
Thanks @shlomi-noach

**Comment by shlomi-noach** [comment] 2016-04-03 06:16
Is it confirmed the problem is solved on mentioned platforms?

**Comment by ikewalker** [comment] 2016-04-04 23:53
I can confirm that the problem is solved on all mentioned platforms that I tested. The one I did not test is MariaDB 1.0.22.

I tested the following versions:

MySQL Community Server 5.5.46
Percona Server 5.6.27
Percona Server 5.7.10-3
MySQL Community Server 5.7.11

I was able to install common_schema 2.3 on all of those versions with no errors, and I was able to successfully run the following QueryScript test:

call common_schema.run("
foreach ($t: select TABLE_NAME 
  FROM INFORMATION_SCHEMA.TABLES 
  WHERE table_schema = 'mysql') 
{select count(*) from mysql.:${t} }
" );

**Comment by genuss** [comment] 2016-04-05 08:05
I can confirm installation works too. Thank you for the fix. One little thing I mentioned is weird symbols in sql-file of release. Take a look for instance on line 13466.

**Comment by tersmitten** [comment] 2016-04-05 10:31
```
Server version: 5.5.48-37.8 Percona Server (GPL), Release 37.8, Revision c8ae1b6
```

also works

**Comment by shlomi-noach** [comment] 2016-04-05 10:33
@genuss thanks - can you kindly open a new issue for the strange chars? Probably my mac's version of `html2text`

**Comment by shlomi-noach** [comment] 2016-04-05 10:33
thanks all, closing this issue

**Closed by shlomi-noach** 2016-04-05 10:33 UTC
